### ISSUE TITLE
A better alternative

### ISSUE THREAD

**Issue by sanelkukic** [ProLife14/super-super-heroku-bot#7]
Heroku isn't recommended for hosting Discord bots, because of the limit where dynos go idle after ~30 minutes.

Instead, why not setup a [#! (hashbang)](https://hashbang.sh) account and host it on their server (you get your own unix user account on their server, plus an `@hashbang.sh` email and access to their IRC chat if you ever need help with anything.

You don't get `sudo` or `root` access to their server, but you can use `systemd --user` so why would you need `sudo` anyways.

You also get a static HTTP server but I don't think you'll need it for this project.

Best part is it's all free. Free as in beer.

Anyways, just a suggestion. You don't have to if you don't want to. Just giving my opinion.

**Comment by aiden2480** [comment]
Hi there xDrixxyz,

I'm also creating a discord bot and also looking for heroku but wishing for a better alternative. Is there any reason why hashbang wouldn't host a python discord bot?

Aiden

**Comment by JettBurns14** [comment]
Hashbang looks pretty cool, thanks for sharing.

Yes, Heroku puts *web dynos* to sleep after 30min of inactivity, but this doesn’t apply to workers, which is the key to my hosting method. The [Dynos FAQ](https://devcenter-staging.heroku.com/articles/free-dyno-hours) explains this:
> If an app has a free web dyno, and that dyno receives no web traffic in a 30-minute period, it will sleep.

> Worker dynos do not sleep, because they do not respond to web requests. Be mindful of this as they may run 24/7 and consume from your pool of hours.

I’d also recommend hooking up some kind of credit card so you get 1000 free hours per month, to insure the bot is online a full month at a time.

Thanks for your issue and suggestion! Closing this now.
