### ISSUE TITLE
It failed

### ISSUE THREAD

**Issue by MMaximum** [ProLife14/super-super-heroku-bot#9]
**_The commands etc for the bot and your scripts it failed for my bot. I Really need a fix for it. Email me if you have the fix at: [email removed] ps my gmail account has scam scanner etc so yeah._**

**Comment by DakrmIshel** [comment]
i failied in wut plz Help me

**Comment by JettBurns14** [comment]
Sorry, but if you don't provide extra information like what you tried, what failed, what errors you're seeing, etc, I can't really help you.
